# SPDX-License-Identifier: GPL-3.0-only
# Copyright (C) 2026 bmad4ever
# See LICENSE for the full GNU GPL v3 text.

"""Large constant lookup tables extracted from lowlevel.py.

Pure data, no logic, no runtime dependencies — kept separate so lowlevel.py
stays focused on node construction and _build_input() logic.
"""

# --- optional-buffer params -------------------------------------------------
# Parameters that cv2 accepts as None (either output buffers it fills via a
# pointer, or masks where None means "the whole image"). They surface as
# optional advanced inputs so users can supply their own buffer / mask.
OPTIONAL_BUFFER_PARAMS = {
	("kmeans", "bestLabels"),
	("solvePnP", "distCoeffs"),
	("solvePnPRansac", "distCoeffs"),
	("projectPoints", "distCoeffs"),
	("undistort", "distCoeffs"),
	# required-in-stub masks that cv2 accepts as None = "the whole image":
	# the photo module's region masks and copyTo's selector. seamlessClone's
	# mask must be SOURCE-sized when given, so forcing a connection just made
	# people wire destination-sized masks that cv2 rejects.
	("seamlessClone", "mask"),
	("colorChange", "mask"),
	("illuminationChange", "mask"),
	("textureFlattening", "mask"),
	("copyTo", "mask"),
	# floodFill's operation mask sits BETWEEN required positionals (image, mask,
	# seedPoint, newVal): passed as a keyword it collides with the positional
	# seedPoint binding to cv2's mask slot ("Overload resolution failed"), so it
	# must go positionally - as None when unconnected (cv2 uses a temp mask).
	# When given it must be (h+2, w+2) uint8; non-zero cells block the fill.
	("floodFill", "mask"),
}

# --- per-function parameter defaults ----------------------------------------
# OpenCV's documented defaults for optional parameters, curated from the C++
# docs (the type stubs only say "= ..."). A curated parameter renders as a
# properly typed widget preset to the value cv2 would use anyway - no
# behavior change out of the box, but no untyped free-text field either.
# Parameters not listed here keep the blank-literal widget (blank = default).
PARAM_DEFAULTS = {  # per-function values where the generic name would be wrong
	# cv2 5.0 additions / Eigen-gated contrib, at OpenCV's own C++ defaults so
	# they render as typed widgets instead of a blank literal field (rule 7)
	("rescaleDepth", "depth_factor"): 1000.0,
	("findTransformECCWithMask", "gaussFiltSize"): 5,
	("filter2Dp", "anchorX"): -1,
	("filter2Dp", "anchorY"): -1,
	("filter2Dp", "scale"): 1.0,
	("filter2Dp", "shift"): 0.0,
	("intensity_transform.BIMEF", "mu"): 0.5,
	("intensity_transform.BIMEF", "a"): -0.3293,
	("intensity_transform.BIMEF", "b"): 1.1258,
	("intensity_transform.BIMEF2", "mu"): 0.5,
	("intensity_transform.BIMEF2", "a"): -0.3293,
	("intensity_transform.BIMEF2", "b"): 1.1258,
	("Laplacian", "ksize"): 1,
	("Sobel", "ksize"): 3,
	("spatialGradient", "ksize"): 3,
	("goodFeaturesToTrack", "k"): 0.04,
	("goodFeaturesToTrackWithQuality", "k"): 0.04,
	("findHomography", "maxIters"): 2000,
	("findHomography", "confidence"): 0.995,
	("findFundamentalMat", "maxIters"): 1000,
	("estimateAffine2D", "maxIters"): 2000,
	("estimateAffinePartial2D", "maxIters"): 2000,
	# 3D point-set registration: cv2's own defaults, so both variants render as
	# typed widgets instead of a blank literal field
	("estimateAffine3D", "ransacThreshold"): 3.0,
	("estimateAffine3D", "force_rotation"): True,
	("findEssentialMat", "threshold"): 1.0,
	("findEssentialMat", "prob"): 0.999,
	("findEssentialMat", "maxIters"): 1000,
	("recoverPose", "prob"): 0.999,
	("recoverPose", "threshold"): 1.0,
	("convertScaleAbs", "alpha"): 1.0,
	("convertScaleAbs", "beta"): 0.0,
	("normalize", "alpha"): 1.0,
	("normalize", "beta"): 0.0,
	("connectedComponents", "connectivity"): 8,
	("connectedComponentsWithStats", "connectivity"): 8,
	# kernel depth (ktype) differs per function: CV_64F vs CV_32F
	("getGaussianKernel", "ktype"): "CV_64F",
	("getDerivKernels", "ktype"): "CV_32F",
	("getGaborKernel", "ktype"): "CV_64F",
	("createHanningWindow", "type"): "CV_32F",
	("stylization", "sigma_s"): 60.0,
	("stylization", "sigma_r"): 0.45,
	("edgePreservingFilter", "sigma_s"): 60.0,
	("edgePreservingFilter", "sigma_r"): 0.4,
	("detailEnhance", "sigma_s"): 10.0,
	("detailEnhance", "sigma_r"): 0.15,
	("pencilSketch", "sigma_s"): 60.0,
	("pencilSketch", "sigma_r"): 0.07,
	("pencilSketch", "shade_factor"): 0.02,
	("convexHull", "clockwise"): False,
	("convexHull", "returnPoints"): True,
	("intersectConvexConvex", "handleNested"): True,
	("contourArea", "oriented"): False,
	# --- rule-7 sweep: every remaining optional float/int/bool ----------------
	# Read off the C++ declarations in the OpenCV 5.x sources, then checked
	# against cv2's own type stub, which is the only place that distinguishes
	# "has a C++ default" from "the Python default really is None":
	#   resize.fx      -> `fx: float = ...`         - a real default, listed here
	#   EMD.lowerBound -> `lowerBound: float|None`  - a pointer arg, NOT listed
	# (temp/_scan_literals.py reproduces the list of params still missing one.)
	# Passing a value equal to cv2's own default is a no-op, so nothing changes
	# for a workflow that left the field blank - blank keeps meaning "omit the
	# argument" in execute().
	("PSNR", "R"): 255.0,
	("approxPolyN", "epsilon_percentage"): -1.0,
	("approxPolyN", "ensure_convex"): True,
	("arrowedLine", "tipLength"): 0.1,
	("batchDistance", "K"): 0,
	("batchDistance", "update"): 0,
	("batchDistance", "crosscheck"): False,
	("calcOpticalFlowPyrLK", "minEigThreshold"): 1e-4,
	("checkRange", "quiet"): True,
	("checkRange", "minVal"): -1.7976931348623157e308,   # -DBL_MAX
	("checkRange", "maxVal"): 1.7976931348623157e308,    # DBL_MAX
	("colorChange", "red_mul"): 1.0,
	("colorChange", "green_mul"): 1.0,
	("colorChange", "blue_mul"): 1.0,
	("completeSymm", "lowerToUpper"): False,
	("cornerMinEigenVal", "ksize"): 3,
	("drawMarker", "markerSize"): 20,
	("estimateAffine2D", "refineIters"): 10,
	("estimateAffinePartial2D", "refineIters"): 10,
	("estimateChessboardSharpness", "rise_distance"): 0.8,
	("estimateChessboardSharpness", "vertical"): False,
	("estimateTranslation3D", "ransacThreshold"): 3.0,
	("fastNlMeansDenoising", "h"): 3.0,
	("fastNlMeansDenoising", "templateWindowSize"): 7,
	("fastNlMeansDenoising", "searchWindowSize"): 21,
	("fastNlMeansDenoisingColored", "h"): 3.0,
	("fastNlMeansDenoisingColored", "hColor"): 3.0,
	("fastNlMeansDenoisingColored", "templateWindowSize"): 7,
	("fastNlMeansDenoisingColored", "searchWindowSize"): 21,
	("findEssentialMat", "focal"): 1.0,
	("getDefaultNewCameraMatrix", "centerPrincipalPoint"): False,
	("getGaborKernel", "psi"): 1.5707963267948966,       # CV_PI * 0.5
	("getOptimalNewCameraMatrix", "centerPrincipalPoint"): False,
	("goodFeaturesToTrackWithQuality", "gradientSize"): 3,
	("HoughLines", "use_edgeval"): False,
	("HoughLinesWithAccumulator", "use_edgeval"): False,
	("illuminationChange", "alpha"): 0.2,
	("illuminationChange", "beta"): 0.4,
	("moments", "binaryImage"): False,
	("patchNaNs", "val"): 0.0,
	("phaseCorrelateIterative", "L2size"): 7,
	("phaseCorrelateIterative", "maxIters"): 10,
	("projectPoints", "aspectRatio"): 0.0,
	("projectPointsSepJ", "aspectRatio"): 0.0,
	("putText", "bottomLeftOrigin"): False,
	("randShuffle", "iterFactor"): 1.0,
	("recoverPose", "focal"): 1.0,
	("reduceArgMax", "lastIndex"): False,
	("reduceArgMin", "lastIndex"): False,
	("registerDepth", "depthDilation"): False,
	("reprojectImageTo3D", "handleMissingValues"): False,
	("resize", "fx"): 0.0,
	("resize", "fy"): 0.0,
	("solvePnP", "useExtrinsicGuess"): False,
	("solvePnPRansac", "useExtrinsicGuess"): False,
	("solvePnPRansac", "iterationsCount"): 100,
	("solvePnPRansac", "reprojectionError"): 8.0,
	("solvePnPRefineVVS", "VVSlambda"): 1.0,
	("solvePoly", "maxIters"): 300,
	("stereoRectify", "alpha"): -1.0,
	("stereoRectifyUncalibrated", "threshold"): 5.0,
	("textureFlattening", "low_threshold"): 30.0,
	("textureFlattening", "high_threshold"): 45.0,
	("textureFlattening", "kernel_size"): 3,
	("validateDisparity", "disp12MaxDisp"): 1,
	# --- opencv-contrib submodules ------------------------------------------
	# Curated from the OpenCV contrib docs, so every optional knob renders as a
	# typed widget preset to the value cv2 would use anyway.
	("xphoto.dctDenoising", "psize"): 16,
	("ximgproc.l0Smooth", "lambda_"): 0.02,
	("ximgproc.l0Smooth", "kappa"): 2.0,
	("ximgproc.rollingGuidanceFilter", "d"): -1,
	("ximgproc.rollingGuidanceFilter", "sigmaColor"): 25.0,
	("ximgproc.rollingGuidanceFilter", "sigmaSpace"): 3.0,
	("ximgproc.rollingGuidanceFilter", "numOfIter"): 4,
	("ximgproc.bilateralTextureFilter", "fr"): 3,
	("ximgproc.bilateralTextureFilter", "numIter"): 1,
	("ximgproc.bilateralTextureFilter", "sigmaAlpha"): -1.0,
	("ximgproc.bilateralTextureFilter", "sigmaAvg"): -1.0,
	("ximgproc.dtFilter", "numIters"): 3,
	("ximgproc.amFilter", "adjust_outliers"): False,
	("ximgproc.weightedMedianFilter", "sigma"): 25.5,
	("ximgproc.fastGlobalSmootherFilter", "lambda_attenuation"): 0.25,
	("ximgproc.fastGlobalSmootherFilter", "num_iter"): 3,
	("ximgproc.niBlackThreshold", "r"): 128.0,
	("ximgproc.guidedFilter", "scale"): 1.0,
	("ximgproc.RadonTransform", "theta"): 1.0,
	("ximgproc.RadonTransform", "start_angle"): 0.0,
	("ximgproc.RadonTransform", "end_angle"): 180.0,
	("ximgproc.RadonTransform", "crop"): False,
	("ximgproc.RadonTransform", "norm"): False,
	("ximgproc.getDisparityVis", "scale"): 1.0,
	("ximgproc.findEllipses", "scoreThreshold"): 0.7,
	("ximgproc.findEllipses", "reliabilityThreshold"): 0.5,
	("ximgproc.findEllipses", "centerDistanceThreshold"): 0.05,
	("ximgproc.fourierDescriptor", "nbElt"): -1,
	("ximgproc.fourierDescriptor", "nbFD"): -1,
	("ximgproc.transformFD", "fdContour"): True,
	("ximgproc.computeBadPixelPercent", "thresh"): 24,
	("ximgproc.fastBilateralSolverFilter", "sigma_spatial"): 8.0,
	("ximgproc.fastBilateralSolverFilter", "sigma_luma"): 8.0,
	("ximgproc.fastBilateralSolverFilter", "sigma_chroma"): 8.0,
	("ximgproc.fastBilateralSolverFilter", "lambda_"): 128.0,
	("ximgproc.fastBilateralSolverFilter", "num_iter"): 25,
	("ximgproc.fastBilateralSolverFilter", "max_tol"): 1e-5,
	("ximgproc.FastHoughTransform", "dstMatDepth"): "CV_32S",
	("img_hash.marrHildrethHash", "alpha"): 2.0,
	("img_hash.marrHildrethHash", "scale"): 1.0,
	("img_hash.radialVarianceHash", "sigma"): 1.0,
	("img_hash.radialVarianceHash", "numOfAngleLine"): 180,
	("optflow.calcOpticalFlowSparseToDense", "grid_step"): 8,
	("optflow.calcOpticalFlowSparseToDense", "k"): 128,
	("optflow.calcOpticalFlowSparseToDense", "sigma"): 0.05,
	("optflow.calcOpticalFlowSparseToDense", "use_post_proc"): True,
	("optflow.calcOpticalFlowSparseToDense", "fgs_lambda"): 500.0,
	("optflow.calcOpticalFlowSparseToDense", "fgs_sigma"): 1.5,
	("motempl.calcMotionGradient", "apertureSize"): 3,
}

# --- drawing data params ----------------------------------------------------
# Non-canvas 'image' params of the drawing functions: they carry a point set or
# a matrix, NOT pixels (fillConvexPoly's `points`, drawFrameAxes' cameraMatrix/
# distCoeffs/rvec/tvec, drawChessboardCorners' `corners`). A MASK/IMAGE link
# here would be a silent type lie, so they accept only an NPARRAY.
DRAWING_DATA_PARAMS = {
	("fillConvexPoly", "points"),
	("drawChessboardCorners", "corners"),
	("drawFrameAxes", "cameraMatrix"),
	("drawFrameAxes", "distCoeffs"),
	("drawFrameAxes", "rvec"),
	("drawFrameAxes", "tvec"),
}

# --- math data params -------------------------------------------------------
# Non-image 'image' params of non-drawing functions: camera matrices, distortion
# coefficients, rotation/translation vectors, PCA eigenvectors, fundamental/
# essential/homography matrices, point sets for geometry, linear-algebra inputs,
# etc.  Same rationale as DRAWING_DATA_PARAMS: a MASK/IMAGE link here would be
# a silent type lie, so they accept only NPARRAY.  Keyed by (func_name, param)
# -- the check lives in _build_input().
MATH_DATA_PARAMS = {
	# --- camera calibration / projection ------------------------------------
	("calibrationMatrixValues", "cameraMatrix"),
	("getDefaultNewCameraMatrix", "cameraMatrix"),
	("getOptimalNewCameraMatrix", "cameraMatrix"),
	("getOptimalNewCameraMatrix", "distCoeffs"),
	("undistort", "cameraMatrix"),
	("undistort", "distCoeffs"),
	("undistortImagePoints", "cameraMatrix"),
	("undistortImagePoints", "distCoeffs"),
	("undistortPoints", "cameraMatrix"),
	("undistortPoints", "distCoeffs"),
	("initUndistortRectifyMap", "cameraMatrix"),
	("initUndistortRectifyMap", "distCoeffs"),
	("initUndistortRectifyMap", "R"),
	("initUndistortRectifyMap", "newCameraMatrix"),
	("initInverseRectificationMap", "cameraMatrix"),
	("initInverseRectificationMap", "distCoeffs"),
	("initInverseRectificationMap", "R"),
	("initInverseRectificationMap", "newCameraMatrix"),
	("projectPoints", "objectPoints"),
	("projectPoints", "rvec"),
	("projectPoints", "tvec"),
	("projectPoints", "cameraMatrix"),
	("projectPoints", "distCoeffs"),
	("projectPointsSepJ", "objectPoints"),
	("projectPointsSepJ", "rvec"),
	("projectPointsSepJ", "tvec"),
	("projectPointsSepJ", "cameraMatrix"),
	("projectPointsSepJ", "distCoeffs"),
	("solvePnP", "objectPoints"),
	("solvePnP", "imagePoints"),
	("solvePnP", "cameraMatrix"),
	("solvePnP", "distCoeffs"),
	("solvePnPRansac", "objectPoints"),
	("solvePnPRansac", "imagePoints"),
	("solvePnPRansac", "cameraMatrix"),
	("solvePnPRansac", "distCoeffs"),
	("solvePnPRefineLM", "objectPoints"),
	("solvePnPRefineLM", "imagePoints"),
	("solvePnPRefineLM", "cameraMatrix"),
	("solvePnPRefineLM", "distCoeffs"),
	("solvePnPRefineLM", "rvec"),
	("solvePnPRefineLM", "tvec"),
	("solvePnPRefineVVS", "objectPoints"),
	("solvePnPRefineVVS", "imagePoints"),
	("solvePnPRefineVVS", "cameraMatrix"),
	("solvePnPRefineVVS", "distCoeffs"),
	("solvePnPRefineVVS", "rvec"),
	("solvePnPRefineVVS", "tvec"),
	("stereoRectify", "cameraMatrix1"),
	("stereoRectify", "distCoeffs1"),
	("stereoRectify", "cameraMatrix2"),
	("stereoRectify", "distCoeffs2"),
	("stereoRectify", "R"),
	("stereoRectify", "T"),
	("stereoRectifyUncalibrated", "points1"),
	("stereoRectifyUncalibrated", "points2"),
	("stereoRectifyUncalibrated", "F"),
	("warpFrame", "Rt"),
	("warpFrame", "cameraMatrix"),
	("reprojectImageTo3D", "Q"),
	("triangulatePoints", "projMatr1"),
	("triangulatePoints", "projMatr2"),
	("triangulatePoints", "projPoints1"),
	("triangulatePoints", "projPoints2"),
	("registerDepth", "unregisteredCameraMatrix"),
	("registerDepth", "registeredCameraMatrix"),
	("registerDepth", "registeredDistCoeffs"),
	("registerDepth", "Rt"),
	("computeCorrespondEpilines", "points"),
	("computeCorrespondEpilines", "F"),
	("correctMatches", "F"),
	("correctMatches", "points1"),
	("correctMatches", "points2"),
	("findTransformECC", "warpMatrix"),
	("findTransformECCWithMask", "warpMatrix"),
	("decomposeProjectionMatrix", "projMatrix"),
	("convertPointsFromHomogeneous", "src"),
	("convertPointsToHomogeneous", "src"),
	("perspectiveTransform", "src"),
	("perspectiveTransform", "m"),
	("transform", "src"),
	("transform", "m"),
	("getAffineTransform", "src"),
	("getAffineTransform", "dst"),
	("getPerspectiveTransform", "src"),
	("getPerspectiveTransform", "dst"),
	("invertAffineTransform", "M"),
	("matMulDeriv", "A"),
	("matMulDeriv", "B"),
	("depthTo3d", "K"),
	("depthTo3dSparse", "in_K"),
	("depthTo3dSparse", "in_points"),
	("sampsonDistance", "pt1"),
	("sampsonDistance", "pt2"),
	("sampsonDistance", "F"),
	("composeRT", "rvec1"),
	("composeRT", "tvec1"),
	("composeRT", "rvec2"),
	("composeRT", "tvec2"),
	("correctChromaticAberration", "coefficients"),
	# --- essential / fundamental / homography --------------------------------
	("findEssentialMat", "points1"),
	("findEssentialMat", "points2"),
	("findEssentialMat", "cameraMatrix"),
	("findEssentialMat", "cameraMatrix1"),
	("findEssentialMat", "distCoeffs1"),
	("findEssentialMat", "cameraMatrix2"),
	("findEssentialMat", "distCoeffs2"),
	("findFundamentalMat", "points1"),
	("findFundamentalMat", "points2"),
	("findHomography", "srcPoints"),
	("findHomography", "dstPoints"),
	("decomposeEssentialMat", "E"),
	("recoverPose", "E"),
	("recoverPose", "points1"),
	("recoverPose", "points2"),
	("recoverPose", "cameraMatrix"),
	("recoverPose", "cameraMatrix1"),
	("recoverPose", "distCoeffs1"),
	("recoverPose", "cameraMatrix2"),
	("recoverPose", "distCoeffs2"),
	# --- PCA / covariance ---------------------------------------------------
	("PCACompute", "data"),
	("PCACompute", "mean"),
	("PCACompute2", "data"),
	("PCACompute2", "mean"),
	("PCAProject", "data"),
	("PCAProject", "mean"),
	("PCAProject", "eigenvectors"),
	("PCABackProject", "data"),
	("PCABackProject", "mean"),
	("PCABackProject", "eigenvectors"),
	("calcCovarMatrix", "samples"),
	("calcCovarMatrix", "mean"),
	# --- randn / randu (distribution parameters, not pixels) ----------------
	("randn", "mean"),
	("randn", "stddev"),
	("randu", "low"),
	("randu", "high"),
	# --- linear algebra (matrix inputs) -------------------------------------
	("SVDecomp", "src"),
	("SVBackSubst", "w"),
	("SVBackSubst", "u"),
	("SVBackSubst", "vt"),
	("SVBackSubst", "rhs"),
	("invert", "src"),
	("determinant", "mtx"),
	("trace", "mtx"),
	("solve", "src1"),
	("solve", "src2"),
	("solveCubic", "coeffs"),
	("solveLP", "Func"),
	("solveLP", "Constr"),
	("solvePoly", "coeffs"),
	("eigen", "src"),
	("eigenNonSymmetric", "src"),
	("completeSymm", "m"),
	("setIdentity", "mtx"),
	("Mahalanobis", "v1"),
	("Mahalanobis", "v2"),
	("Mahalanobis", "icovar"),
	("gemm", "src1"),
	("gemm", "src2"),
	("gemm", "src3"),
	("mulTransposed", "src"),
	("sort", "src"),
	("sortIdx", "src"),
	("Rodrigues", "src"),
	("divSpectrums", "a"),
	("divSpectrums", "b"),
	("mulSpectrums", "a"),
	("mulSpectrums", "b"),
	("dct", "src"),
	("idct", "src"),
	("dft", "src"),
	("idft", "src"),
	# --- point sets / contour geometry (Nx1x2 arrays, not images) ------------
	("boundingRect", "array"),
	("contourArea", "contour"),
	("convexHull", "points"),
	("convexityDefects", "contour"),
	("convexityDefects", "convexhull"),
	("arcLength", "curve"),
	("approxPolyDP", "curve"),
	("approxPolyN", "curve"),
	("isContourConvex", "contour"),
	("fitEllipse", "points"),
	("fitEllipseAMS", "points"),
	("fitEllipseDirect", "points"),
	("fitLine", "points"),
	("minAreaRect", "points"),
	("minEnclosingCircle", "points"),
	("minEnclosingTriangle", "points"),
	("minEnclosingConvexPolygon", "points"),
	("matchShapes", "contour1"),
	("matchShapes", "contour2"),
	("pointPolygonTest", "contour"),
	("intersectConvexConvex", "p1"),
	("intersectConvexConvex", "p2"),
	("getClosestEllipsePoints", "points"),
	("findNonZero", "src"),
	("HoughLinesPointSet", "point"),
	("compareHist", "H1"),
	("compareHist", "H2"),
	# --- tracking / estimation point sets (Nx1x2 / Nx2 / Nx3) ---------------
	("calcOpticalFlowPyrLK", "prevPts"),
	("calcOpticalFlowPyrLK", "nextPts"),
	("cornerSubPix", "corners"),
	("find4QuadCornerSubpix", "corners"),
	("estimateChessboardSharpness", "corners"),
	("estimateAffine2D", "from_"),
	("estimateAffine2D", "to"),
	("estimateAffine3D", "src"),
	("estimateAffine3D", "dst"),
	("estimateAffinePartial2D", "from_"),
	("estimateAffinePartial2D", "to"),
	("estimateTranslation3D", "src"),
	("estimateTranslation3D", "dst"),
	# --- feature descriptor matrices -----------------------------------------
	("batchDistance", "src1"),
	("batchDistance", "src2"),
	("EMD", "signature1"),
	("EMD", "signature2"),
	# --- clustering / model data ---------------------------------------------
	("kmeans", "data"),
	("kmeans", "bestLabels"),
	("grabCut", "bgdModel"),
	("grabCut", "fgdModel"),
	# --- kernel / filter data (not images) ----------------------------------
	("filter2D", "kernel"),
	("filter2Dp", "kernel"),
	("morphologyEx", "kernel"),
	("dilate", "kernel"),
	("erode", "kernel"),
	("sepFilter2D", "kernelX"),
	("sepFilter2D", "kernelY"),
	("remap", "map1"),
	("remap", "map2"),
	("convertMaps", "map1"),
	("convertMaps", "map2"),
	("warpAffine", "M"),
	("warpPerspective", "M"),
	("broadcast", "shape"),
}
