# SPDX-License-Identifier: GPL-3.0-only
# Copyright (C) 2026 bmad4ever
# Adapted from geroldmeisinger/opencv-comfyui (GPL-3.0).
# See LICENSE for the full GNU GPL v3 text.

# Auto-generated by generator/generator.py -- do not edit by hand.
# Generated from the cv2 5.1.0-dev SUBMODULE type stubs
# (Error, alphamat, aruco, barcode, bgsegm, bioinspired, ccm, colored_kinfu, datasets, detail, dnn, dnn_superres, dpm, dynafu, face, fisheye, flann, ft, hfs, img_hash, instr, intensity_transform, kinfu, large_kinfu, legacy, line_descriptor, linemod, mcc, motempl, multicalib, ocl, omnidir, optflow, parallel, phase_unwrapping, plot, ppf_match_3d, quality, rapid, reg, saliency, segmentation, sfm, signal, slam, stereo, structured_light, text, videostab, viz3d, wechat_qrcode, xfeatures2d, ximgproc, xphoto).
#
# Same entry format as registry.py, except func_name is DOTTED
# ('xphoto.oilPainting') and lowlevel.py resolves it with a nested
# getattr on cv2. Most of these modules only exist in
# opencv-contrib-python(-headless) builds; lowlevel.py skips any entry the
# installed build does not expose, so a core-only install just gets
# fewer nodes instead of failing to import.
#
# Each entry: (func_name, variant_index, n_variants, params, returns)
#   params : list of (param_name, kind, optional) with kind in
#            {'image', 'int', 'float', 'bool', 'str', 'any', and the
#            composite kinds 'point2i', 'point2f', 'size', 'scalar',
#            'rect', 'rotatedrect', 'termcriteria', 'moments', 'range'}
#   returns: list of kinds

CONTRIB_FUNCTIONS = [
	('alphamat.infoFlow', 0, 1, [('image', 'image', 0), ('tmap', 'image', 0)], ['image']),
	('aruco.drawDetectedCornersCharuco', 0, 1, [('image', 'image', 0), ('charucoCorners', 'image', 0), ('cornerColor', 'scalar', 1)], ['image']),
	('ccm.gammaCorrection', 0, 1, [('src', 'image', 0), ('gamma', 'float', 0)], ['image']),
	('detail.createWeightMap', 0, 1, [('mask', 'image', 0), ('sharpness', 'float', 0), ('weight', 'image', 0)], ['image']),
	('detail.normalizeUsingWeightMap', 0, 1, [('weight', 'image', 0), ('src', 'image', 0)], ['image']),
	('detail.overlapRoi', 0, 1, [('tl1', 'point2i', 0), ('tl2', 'point2i', 0), ('sz1', 'size', 0), ('sz2', 'size', 0), ('roi', 'rect', 0)], ['bool']),
	('detail.stitchingLogLevel', 0, 1, [], ['int']),
	('dnn.blobFromImage', 0, 1, [('image', 'image', 0), ('scalefactor', 'float', 1), ('size', 'size', 1), ('mean', 'scalar', 1), ('swapRB', 'bool', 1), ('crop', 'bool', 1), ('ddepth', 'int', 1)], ['image']),
	('dnn.getInferenceEngineBackendType', 0, 1, [], ['str']),
	('dnn.getInferenceEngineCPUType', 0, 1, [], ['str']),
	('dnn.getInferenceEngineVPUType', 0, 1, [], ['str']),
	('dnn.readTensorFromONNX', 0, 1, [('path', 'str', 0)], ['image']),
	('dnn.setInferenceEngineBackendType', 0, 1, [('newBackendType', 'str', 0)], ['str']),
	('face.drawFacemarks', 0, 1, [('image', 'image', 0), ('points', 'image', 0), ('color', 'scalar', 1)], ['image']),
	('face.getFacesHAAR', 0, 1, [('image', 'image', 0), ('face_cascade_name', 'str', 0)], ['bool', 'image']),
	('face.loadFacePoints', 0, 1, [('filename', 'str', 0), ('offset', 'float', 1)], ['bool', 'image']),
	('fisheye.distortPoints', 0, 2, [('undistorted', 'image', 0), ('K', 'image', 0), ('D', 'image', 0), ('alpha', 'float', 1)], ['image']),
	('fisheye.distortPoints', 1, 2, [('undistorted', 'image', 0), ('Kundistorted', 'image', 0), ('K', 'image', 0), ('D', 'image', 0), ('alpha', 'float', 1)], ['image']),
	('fisheye.estimateNewCameraMatrixForUndistortRectify', 0, 1, [('K', 'image', 0), ('D', 'image', 0), ('image_size', 'size', 0), ('R', 'image', 0), ('balance', 'float', 1), ('new_size', 'size', 1), ('fov_scale', 'float', 1)], ['image']),
	('fisheye.initUndistortRectifyMap', 0, 1, [('K', 'image', 0), ('D', 'image', 0), ('R', 'image', 0), ('P', 'image', 0), ('size', 'size', 0), ('m1type', 'int', 0)], ['image', 'image']),
	('fisheye.projectPoints', 0, 1, [('objectPoints', 'image', 0), ('rvec', 'image', 0), ('tvec', 'image', 0), ('K', 'image', 0), ('D', 'image', 0), ('alpha', 'float', 1)], ['image', 'image']),
	('fisheye.solvePnP', 0, 1, [('objectPoints', 'image', 0), ('imagePoints', 'image', 0), ('cameraMatrix', 'image', 0), ('distCoeffs', 'image', 0), ('useExtrinsicGuess', 'bool', 1), ('flags', 'int', 1), ('criteria', 'termcriteria', 1)], ['bool', 'image', 'image']),
	('fisheye.solvePnPRansac', 0, 1, [('objectPoints', 'image', 0), ('imagePoints', 'image', 0), ('cameraMatrix', 'image', 0), ('distCoeffs', 'image', 0), ('useExtrinsicGuess', 'bool', 1), ('iterationsCount', 'int', 1), ('reprojectionError', 'float', 1), ('confidence', 'float', 1), ('flags', 'int', 1), ('criteria', 'termcriteria', 1)], ['bool', 'image', 'image', 'image']),
	('fisheye.stereoRectify', 0, 1, [('K1', 'image', 0), ('D1', 'image', 0), ('K2', 'image', 0), ('D2', 'image', 0), ('imageSize', 'size', 0), ('R', 'image', 0), ('tvec', 'image', 0), ('flags', 'int', 0), ('newImageSize', 'size', 1), ('balance', 'float', 1), ('fov_scale', 'float', 1)], ['image', 'image', 'image', 'image', 'image']),
	('fisheye.undistortImage', 0, 1, [('distorted', 'image', 0), ('K', 'image', 0), ('D', 'image', 0), ('new_size', 'size', 1)], ['image']),
	('fisheye.undistortPoints', 0, 1, [('distorted', 'image', 0), ('K', 'image', 0), ('D', 'image', 0), ('criteria', 'termcriteria', 1)], ['image']),
	('ft.FT02D_FL_process', 0, 1, [('matrix', 'image', 0), ('radius', 'int', 0)], ['image']),
	('ft.FT02D_FL_process_float', 0, 1, [('matrix', 'image', 0), ('radius', 'int', 0)], ['image']),
	('ft.FT02D_components', 0, 1, [('matrix', 'image', 0), ('kernel', 'image', 0), ('mask', 'image', 1)], ['image']),
	('ft.FT02D_inverseFT', 0, 1, [('components', 'image', 0), ('kernel', 'image', 0), ('width', 'int', 0), ('height', 'int', 0)], ['image']),
	('ft.FT02D_iteration', 0, 1, [('matrix', 'image', 0), ('kernel', 'image', 0), ('mask', 'image', 0), ('firstStop', 'bool', 0), ('maskOutput', 'image', 1)], ['int', 'image', 'image']),
	('ft.FT02D_process', 0, 1, [('matrix', 'image', 0), ('kernel', 'image', 0), ('mask', 'image', 1)], ['image']),
	('ft.FT12D_components', 0, 1, [('matrix', 'image', 0), ('kernel', 'image', 0)], ['image']),
	('ft.FT12D_createPolynomMatrixHorizontal', 0, 1, [('radius', 'int', 0), ('chn', 'int', 0)], ['image']),
	('ft.FT12D_createPolynomMatrixVertical', 0, 1, [('radius', 'int', 0), ('chn', 'int', 0)], ['image']),
	('ft.FT12D_inverseFT', 0, 1, [('components', 'image', 0), ('kernel', 'image', 0), ('width', 'int', 0), ('height', 'int', 0)], ['image']),
	('ft.FT12D_polynomial', 0, 1, [('matrix', 'image', 0), ('kernel', 'image', 0), ('mask', 'image', 1)], ['image', 'image', 'image', 'image']),
	('ft.FT12D_process', 0, 1, [('matrix', 'image', 0), ('kernel', 'image', 0), ('mask', 'image', 1)], ['image']),
	('ft.createKernel', 0, 1, [('function', 'int', 0), ('radius', 'int', 0), ('chn', 'int', 0)], ['image']),
	('ft.createKernel1', 0, 1, [('A', 'image', 0), ('B', 'image', 0), ('chn', 'int', 0)], ['image']),
	('ft.filter', 0, 1, [('image', 'image', 0), ('kernel', 'image', 0)], ['image']),
	('ft.inpaint', 0, 1, [('image', 'image', 0), ('mask', 'image', 0), ('radius', 'int', 0), ('function', 'int', 0), ('algorithm', 'int', 0)], ['image']),
	('img_hash.averageHash', 0, 1, [('inputArr', 'image', 0)], ['image']),
	('img_hash.blockMeanHash', 0, 1, [('inputArr', 'image', 0), ('mode', 'int', 1)], ['image']),
	('img_hash.colorMomentHash', 0, 1, [('inputArr', 'image', 0)], ['image']),
	('img_hash.marrHildrethHash', 0, 1, [('inputArr', 'image', 0), ('alpha', 'float', 1), ('scale', 'float', 1)], ['image']),
	('img_hash.pHash', 0, 1, [('inputArr', 'image', 0)], ['image']),
	('img_hash.radialVarianceHash', 0, 1, [('inputArr', 'image', 0), ('sigma', 'float', 1), ('numOfAngleLine', 'int', 1)], ['image']),
	('intensity_transform.BIMEF', 0, 1, [('input', 'image', 0), ('mu', 'float', 1), ('a', 'float', 1), ('b', 'float', 1)], ['image']),
	('intensity_transform.BIMEF2', 0, 1, [('input', 'image', 0), ('k', 'float', 0), ('mu', 'float', 0), ('a', 'float', 0), ('b', 'float', 0)], ['image']),
	('intensity_transform.autoscaling', 0, 1, [('input', 'image', 0)], ['image']),
	('intensity_transform.contrastStretching', 0, 1, [('input', 'image', 0), ('r1', 'int', 0), ('s1', 'int', 0), ('r2', 'int', 0), ('s2', 'int', 0)], ['image']),
	('intensity_transform.gammaCorrection', 0, 1, [('input', 'image', 0), ('gamma', 'float', 0)], ['image']),
	('intensity_transform.logTransform', 0, 1, [('input', 'image', 0)], ['image']),
	('linemod.colormap', 0, 1, [('quantized', 'image', 0)], ['image']),
	('motempl.calcGlobalOrientation', 0, 1, [('orientation', 'image', 0), ('mask', 'image', 0), ('mhi', 'image', 0), ('timestamp', 'float', 0), ('duration', 'float', 0)], ['float']),
	('motempl.calcMotionGradient', 0, 1, [('mhi', 'image', 0), ('delta1', 'float', 0), ('delta2', 'float', 0), ('mask', 'image', 1), ('apertureSize', 'int', 1)], ['image', 'image']),
	('motempl.updateMotionHistory', 0, 1, [('silhouette', 'image', 0), ('mhi', 'image', 0), ('timestamp', 'float', 0), ('duration', 'float', 0)], ['image']),
	('ocl.haveAmdBlas', 0, 1, [], ['bool']),
	('ocl.haveAmdFft', 0, 1, [], ['bool']),
	('ocl.haveOpenCL', 0, 1, [], ['bool']),
	('ocl.useOpenCL', 0, 1, [], ['bool']),
	('omnidir.initUndistortRectifyMap', 0, 1, [('K', 'image', 0), ('D', 'image', 0), ('xi', 'image', 0), ('R', 'image', 0), ('P', 'image', 0), ('size', 'size', 0), ('m1type', 'int', 0), ('flags', 'int', 0)], ['image', 'image']),
	('omnidir.projectPoints', 0, 1, [('objectPoints', 'image', 0), ('rvec', 'image', 0), ('tvec', 'image', 0), ('K', 'image', 0), ('xi', 'float', 0), ('D', 'image', 0)], ['image', 'image']),
	('omnidir.stereoReconstruct', 0, 1, [('image1', 'image', 0), ('image2', 'image', 0), ('K1', 'image', 0), ('D1', 'image', 0), ('xi1', 'image', 0), ('K2', 'image', 0), ('D2', 'image', 0), ('xi2', 'image', 0), ('R', 'image', 0), ('T', 'image', 0), ('flag', 'int', 0), ('numDisparities', 'int', 0), ('SADWindowSize', 'int', 0), ('newSize', 'size', 1), ('pointType', 'int', 1)], ['image', 'image', 'image', 'image']),
	('omnidir.stereoRectify', 0, 1, [('R', 'image', 0), ('T', 'image', 0)], ['image', 'image']),
	('omnidir.undistortImage', 0, 1, [('distorted', 'image', 0), ('K', 'image', 0), ('D', 'image', 0), ('xi', 'image', 0), ('flags', 'int', 0), ('new_size', 'size', 1)], ['image']),
	('omnidir.undistortPoints', 0, 1, [('distorted', 'image', 0), ('K', 'image', 0), ('D', 'image', 0), ('xi', 'image', 0), ('R', 'image', 0)], ['image']),
	('optflow.calcOpticalFlowSF', 0, 2, [('from_', 'image', 0), ('to', 'image', 0), ('layers', 'int', 0), ('averaging_block_size', 'int', 0), ('max_flow', 'int', 0)], ['image']),
	('optflow.calcOpticalFlowSF', 1, 2, [('from_', 'image', 0), ('to', 'image', 0), ('layers', 'int', 0), ('averaging_block_size', 'int', 0), ('max_flow', 'int', 0), ('sigma_dist', 'float', 0), ('sigma_color', 'float', 0), ('postprocess_window', 'int', 0), ('sigma_dist_fix', 'float', 0), ('sigma_color_fix', 'float', 0), ('occ_thr', 'float', 0), ('upscale_averaging_radius', 'int', 0), ('upscale_sigma_dist', 'float', 0), ('upscale_sigma_color', 'float', 0), ('speed_up_thr', 'float', 0)], ['image']),
	('optflow.calcOpticalFlowSparseToDense', 0, 1, [('from_', 'image', 0), ('to', 'image', 0), ('grid_step', 'int', 1), ('k', 'int', 1), ('sigma', 'float', 1), ('use_post_proc', 'bool', 1), ('fgs_lambda', 'float', 1), ('fgs_sigma', 'float', 1)], ['image']),
	('parallel.setParallelForBackend', 0, 1, [('backendName', 'str', 0), ('propagateNumThreads', 'bool', 1)], ['bool']),
	('ppf_match_3d.addNoisePC', 0, 1, [('pc', 'image', 0), ('scale', 'float', 0)], ['image']),
	('ppf_match_3d.loadPLYSimple', 0, 1, [('fileName', 'str', 0), ('withNormals', 'int', 1)], ['image']),
	('rapid.convertCorrespondencies', 0, 1, [('cols', 'image', 0), ('srcLocations', 'image', 0), ('mask', 'image', 1)], ['image', 'image']),
	('rapid.drawCorrespondencies', 0, 1, [('bundle', 'image', 0), ('cols', 'image', 0)], ['image']),
	('rapid.drawSearchLines', 0, 1, [('img', 'image', 0), ('locations', 'image', 0), ('color', 'scalar', 0)], ['image']),
	('rapid.drawWireframe', 0, 1, [('img', 'image', 0), ('pts2d', 'image', 0), ('tris', 'image', 0), ('color', 'scalar', 0), ('type', 'int', 1), ('cullBackface', 'bool', 1)], ['image']),
	('rapid.extractControlPoints', 0, 1, [('num', 'int', 0), ('len', 'int', 0), ('pts3d', 'image', 0), ('rvec', 'image', 0), ('tvec', 'image', 0), ('K', 'image', 0), ('imsize', 'size', 0), ('tris', 'image', 0)], ['image', 'image']),
	('rapid.extractLineBundle', 0, 1, [('len', 'int', 0), ('ctl2d', 'image', 0), ('img', 'image', 0)], ['image', 'image']),
	('rapid.findCorrespondencies', 0, 1, [('bundle', 'image', 0)], ['image', 'image']),
	('rapid.rapid', 0, 1, [('img', 'image', 0), ('num', 'int', 0), ('len', 'int', 0), ('pts3d', 'image', 0), ('tris', 'image', 0), ('K', 'image', 0), ('rvec', 'image', 0), ('tvec', 'image', 0)], ['float', 'image', 'image', 'float']),
	('sfm.KRtFromProjection', 0, 1, [('P', 'image', 0)], ['image', 'image', 'image']),
	('sfm.applyTransformationToPoints', 0, 1, [('points', 'image', 0), ('T', 'image', 0)], ['image']),
	('sfm.depth', 0, 1, [('R', 'image', 0), ('t', 'image', 0), ('X', 'image', 0)], ['float']),
	('sfm.essentialFromFundamental', 0, 1, [('F', 'image', 0), ('K1', 'image', 0), ('K2', 'image', 0)], ['image']),
	('sfm.essentialFromRt', 0, 1, [('R1', 'image', 0), ('t1', 'image', 0), ('R2', 'image', 0), ('t2', 'image', 0)], ['image']),
	('sfm.euclideanToHomogeneous', 0, 1, [('src', 'image', 0)], ['image']),
	('sfm.fundamentalFromCorrespondences7PointRobust', 0, 1, [('x1', 'image', 0), ('x2', 'image', 0), ('max_error', 'float', 0), ('outliers_probability', 'float', 1)], ['float', 'image', 'image']),
	('sfm.fundamentalFromCorrespondences8PointRobust', 0, 1, [('x1', 'image', 0), ('x2', 'image', 0), ('max_error', 'float', 0), ('outliers_probability', 'float', 1)], ['float', 'image', 'image']),
	('sfm.fundamentalFromEssential', 0, 1, [('E', 'image', 0), ('K1', 'image', 0), ('K2', 'image', 0)], ['image']),
	('sfm.fundamentalFromProjections', 0, 1, [('P1', 'image', 0), ('P2', 'image', 0)], ['image']),
	('sfm.homogeneousToEuclidean', 0, 1, [('src', 'image', 0)], ['image']),
	('sfm.isotropicPreconditionerFromPoints', 0, 1, [('points', 'image', 0)], ['image']),
	('sfm.meanAndVarianceAlongRows', 0, 1, [('A', 'image', 0)], ['image', 'image']),
	('sfm.normalizeFundamental', 0, 1, [('F', 'image', 0)], ['image']),
	('sfm.normalizeIsotropicPoints', 0, 1, [('points', 'image', 0)], ['image', 'image']),
	('sfm.normalizePoints', 0, 1, [('points', 'image', 0)], ['image', 'image']),
	('sfm.normalizedEightPointSolver', 0, 1, [('x1', 'image', 0), ('x2', 'image', 0)], ['image']),
	('sfm.preconditionerFromPoints', 0, 1, [('points', 'image', 0)], ['image']),
	('sfm.projectionFromKRt', 0, 1, [('K', 'image', 0), ('R', 'image', 0), ('t', 'image', 0)], ['image']),
	('sfm.projectionsFromFundamental', 0, 1, [('F', 'image', 0)], ['image', 'image']),
	('sfm.relativeCameraMotion', 0, 1, [('R1', 'image', 0), ('t1', 'image', 0), ('R2', 'image', 0), ('t2', 'image', 0)], ['image', 'image']),
	('sfm.skew', 0, 1, [('x', 'image', 0)], ['image']),
	('signal.resampleSignal', 0, 1, [('inputSignal', 'image', 0), ('inFreq', 'int', 0), ('outFreq', 'int', 0)], ['image']),
	('ximgproc.FastHoughTransform', 0, 1, [('src', 'image', 0), ('dstMatDepth', 'int', 0), ('angleRange', 'int', 1), ('op', 'int', 1), ('makeSkew', 'int', 1)], ['image']),
	('ximgproc.GradientDericheX', 0, 1, [('op', 'image', 0), ('alpha', 'float', 0), ('omega', 'float', 0)], ['image']),
	('ximgproc.GradientDericheY', 0, 1, [('op', 'image', 0), ('alpha', 'float', 0), ('omega', 'float', 0)], ['image']),
	('ximgproc.PeiLinNormalization', 0, 1, [('I', 'image', 0)], ['image']),
	('ximgproc.RadonTransform', 0, 1, [('src', 'image', 0), ('theta', 'float', 1), ('start_angle', 'float', 1), ('end_angle', 'float', 1), ('crop', 'bool', 1), ('norm', 'bool', 1)], ['image']),
	('ximgproc.amFilter', 0, 1, [('joint', 'image', 0), ('src', 'image', 0), ('sigma_s', 'float', 0), ('sigma_r', 'float', 0), ('adjust_outliers', 'bool', 1)], ['image']),
	('ximgproc.anisotropicDiffusion', 0, 1, [('src', 'image', 0), ('alpha', 'float', 0), ('K', 'float', 0), ('niters', 'int', 0)], ['image']),
	('ximgproc.bilateralTextureFilter', 0, 1, [('src', 'image', 0), ('fr', 'int', 1), ('numIter', 'int', 1), ('sigmaAlpha', 'float', 1), ('sigmaAvg', 'float', 1)], ['image']),
	('ximgproc.colorMatchTemplate', 0, 1, [('img', 'image', 0), ('templ', 'image', 0)], ['image']),
	('ximgproc.computeBadPixelPercent', 0, 1, [('GT', 'image', 0), ('src', 'image', 0), ('ROI', 'rect', 0), ('thresh', 'int', 1)], ['float']),
	('ximgproc.computeMSE', 0, 1, [('GT', 'image', 0), ('src', 'image', 0), ('ROI', 'rect', 0)], ['float']),
	('ximgproc.contourSampling', 0, 1, [('src', 'image', 0), ('nbElt', 'int', 0)], ['image']),
	('ximgproc.covarianceEstimation', 0, 1, [('src', 'image', 0), ('windowRows', 'int', 0), ('windowCols', 'int', 0)], ['image']),
	('ximgproc.createQuaternionImage', 0, 1, [('img', 'image', 0)], ['image']),
	('ximgproc.dtFilter', 0, 1, [('guide', 'image', 0), ('src', 'image', 0), ('sigmaSpatial', 'float', 0), ('sigmaColor', 'float', 0), ('mode', 'int', 1), ('numIters', 'int', 1)], ['image']),
	('ximgproc.edgePreservingFilter', 0, 1, [('src', 'image', 0), ('d', 'int', 0), ('threshold', 'float', 0)], ['image']),
	('ximgproc.fastBilateralSolverFilter', 0, 1, [('guide', 'image', 0), ('src', 'image', 0), ('confidence', 'image', 0), ('sigma_spatial', 'float', 1), ('sigma_luma', 'float', 1), ('sigma_chroma', 'float', 1), ('lambda_', 'float', 1), ('num_iter', 'int', 1), ('max_tol', 'float', 1)], ['image']),
	('ximgproc.fastGlobalSmootherFilter', 0, 1, [('guide', 'image', 0), ('src', 'image', 0), ('lambda_', 'float', 0), ('sigma_color', 'float', 0), ('lambda_attenuation', 'float', 1), ('num_iter', 'int', 1)], ['image']),
	('ximgproc.findEllipses', 0, 1, [('image', 'image', 0), ('scoreThreshold', 'float', 1), ('reliabilityThreshold', 'float', 1), ('centerDistanceThreshold', 'float', 1)], ['image']),
	('ximgproc.fourierDescriptor', 0, 1, [('src', 'image', 0), ('nbElt', 'int', 1), ('nbFD', 'int', 1)], ['image']),
	('ximgproc.getDisparityVis', 0, 1, [('src', 'image', 0), ('scale', 'float', 1)], ['image']),
	('ximgproc.guidedFilter', 0, 1, [('guide', 'image', 0), ('src', 'image', 0), ('radius', 'int', 0), ('eps', 'float', 0), ('dDepth', 'int', 1), ('scale', 'float', 1)], ['image']),
	('ximgproc.jointBilateralFilter', 0, 1, [('joint', 'image', 0), ('src', 'image', 0), ('d', 'int', 0), ('sigmaColor', 'float', 0), ('sigmaSpace', 'float', 0), ('borderType', 'int', 1)], ['image']),
	('ximgproc.l0Smooth', 0, 1, [('src', 'image', 0), ('lambda_', 'float', 1), ('kappa', 'float', 1)], ['image']),
	('ximgproc.niBlackThreshold', 0, 1, [('_src', 'image', 0), ('maxValue', 'float', 0), ('type', 'int', 0), ('blockSize', 'int', 0), ('k', 'float', 0), ('binarizationMethod', 'int', 1), ('r', 'float', 1)], ['image']),
	('ximgproc.qconj', 0, 1, [('qimg', 'image', 0)], ['image']),
	('ximgproc.qdft', 0, 1, [('img', 'image', 0), ('flags', 'int', 0), ('sideLeft', 'bool', 0)], ['image']),
	('ximgproc.qmultiply', 0, 1, [('src1', 'image', 0), ('src2', 'image', 0)], ['image']),
	('ximgproc.qunitary', 0, 1, [('qimg', 'image', 0)], ['image']),
	('ximgproc.rollingGuidanceFilter', 0, 1, [('src', 'image', 0), ('d', 'int', 1), ('sigmaColor', 'float', 1), ('sigmaSpace', 'float', 1), ('numOfIter', 'int', 1), ('borderType', 'int', 1)], ['image']),
	('ximgproc.thinning', 0, 1, [('src', 'image', 0), ('thinningType', 'int', 1)], ['image']),
	('ximgproc.transformFD', 0, 1, [('src', 'image', 0), ('t', 'image', 0), ('fdContour', 'bool', 1)], ['image']),
	('ximgproc.weightedMedianFilter', 0, 1, [('joint', 'image', 0), ('src', 'image', 0), ('r', 'int', 0), ('sigma', 'float', 1), ('weightType', 'int', 1), ('mask', 'image', 1)], ['image']),
	('xphoto.applyChannelGains', 0, 1, [('src', 'image', 0), ('gainB', 'float', 0), ('gainG', 'float', 0), ('gainR', 'float', 0)], ['image']),
	('xphoto.dctDenoising', 0, 1, [('src', 'image', 0), ('sigma', 'float', 0), ('psize', 'int', 1)], ['image']),
	('xphoto.inpaint', 0, 1, [('src', 'image', 0), ('mask', 'image', 0), ('algorithmType', 'int', 0)], ['image']),
	('xphoto.oilPainting', 0, 2, [('src', 'image', 0), ('size', 'int', 0), ('dynRatio', 'int', 0), ('code', 'int', 0)], ['image']),
	('xphoto.oilPainting', 1, 2, [('src', 'image', 0), ('size', 'int', 0), ('dynRatio', 'int', 0)], ['image']),
]

# Functions whose result is delivered by writing into an argument
# instead of being returned (they return None). The out-parameter is
# NOT an input above; lowlevel.py allocates a buffer shaped like the
# reference input, passes it positionally in the out-parameter's
# original slot, and returns it as the node's image output.
#   {qualified_name: (out_param_name, reference_param_name)}
INPLACE_OUT_PARAMS = {'intensity_transform.autoscaling': ('output', 'input', 1), 'intensity_transform.contrastStretching': ('output', 'input', 1), 'intensity_transform.gammaCorrection': ('output', 'input', 1), 'intensity_transform.logTransform': ('output', 'input', 1), 'xphoto.dctDenoising': ('dst', 'src', 1), 'xphoto.inpaint': ('dst', 'src', 2)}

# Functions that OpenCV compiles out unless it was built WITH EIGEN. They
# are exposed on purpose (a build that has Eigen runs them from this same
# API); lowlevel.py adds the requirement to the node description, checking
# cv2.getBuildInformation() so an Eigen-less build says so up front instead
# of raising a bare (-213) at execution time. Generator source of truth:
# generator/generator.py:EIGEN_GATED.
EIGEN_GATED = set(['intensity_transform.BIMEF', 'intensity_transform.BIMEF2', 'ximgproc.fastBilateralSolverFilter'])
